CREATE TABLE admin (
  id         INTEGER NOT NULL PRIMARY KEY,
  admin_user VARCHAR(20),
  admin_pwd  VARCHAR(50)
);

CREATE TABLE msg (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  content     VARCHAR(300)                             NOT NULL,
  name        VARCHAR(50)                              NOT NULL,
  phone       VARCHAR(50),
  email       VARCHAR(50),
  qq          VARCHAR(16),
  ip          VARCHAR(20),
  status      SMALLINT DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL
);
